import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDate;

class GenerateBillForm extends JFrame implements ActionListener {

    // UI Components
    JLabel lBillId, lCustId, lDate, lTotal, lMedicine, lQuantity;
    JTextField tBillId, tCustId, tDate, tTotal, tQuantity;
    JButton bGenerate, bBack, bAddMedicine;
    JComboBox<String> cbMedicine;
    JTable table;
    DefaultTableModel model;
    
    // NOTE: Replace this with your actual DB configuration details
    private static class DatabaseConfig {
        static final String URL = "jdbc:mysql://localhost:3306/project"; // Replace with your actual URL
        static final String USER = "root";
        static final String PASSWORD = "VISHESHSQL123@";
    }

    public GenerateBillForm() {
        // --- UI Setup (Simplified for display) ---
        setTitle("Generate Bill");
        setSize(650, 500);
        setLayout(null);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setBackground(new Color(194, 217, 220));

        // Bill ID (Now shows 'TBD' and is non-editable)
        lBillId = new JLabel("Bill ID:"); lBillId.setBounds(50, 20, 100, 25); add(lBillId);
        // *** CORRECTION 1: Initializing Bill ID as TBD and making it non-editable ***
        tBillId = new JTextField("TBD (Auto-Generated)");
        tBillId.setBounds(180, 20, 150, 25);
        tBillId.setEditable(false); // Bill ID is generated by the DB
        add(tBillId);

        // Customer ID
        lCustId = new JLabel("Customer ID:"); lCustId.setBounds(50, 60, 100, 25); add(lCustId);
        tCustId = new JTextField(); tCustId.setBounds(180, 60, 150, 25); add(tCustId);

        // Date
        lDate = new JLabel("Date (YYYY-MM-DD):"); lDate.setBounds(50, 100, 150, 25); add(lDate);
        tDate = new JTextField(LocalDate.now().toString()); tDate.setBounds(180, 100, 150, 25); add(tDate);

        // Medicine selection (rest of UI setup remains the same)
        lMedicine = new JLabel("Medicine:"); lMedicine.setBounds(50, 140, 100, 25); add(lMedicine);
        cbMedicine = new JComboBox<>(); cbMedicine.setBounds(180, 140, 200, 25); add(cbMedicine);
        loadMedicines(); 

        // Quantity
        lQuantity = new JLabel("Quantity:"); lQuantity.setBounds(50, 180, 100, 25); add(lQuantity);
        tQuantity = new JTextField("1"); tQuantity.setBounds(180, 180, 50, 25); add(tQuantity);

        // Add medicine button
        bAddMedicine = new JButton("Add Medicine"); bAddMedicine.setBounds(250, 180, 150, 25); add(bAddMedicine);
        bAddMedicine.addActionListener(this);

        // Table for medicines: Medicine, Quantity, Price, Amount, [Hidden Med ID]
        model = new DefaultTableModel(new String[]{"Medicine", "Quantity", "Price", "Amount", "Med ID"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; } 
        };
        table = new JTable(model);
        
        // Hide the Med ID column (index 4)
        table.getColumnModel().getColumn(4).setMinWidth(0);
        table.getColumnModel().getColumn(4).setMaxWidth(0);
        table.getColumnModel().getColumn(4).setWidth(0);

        JScrollPane scroll = new JScrollPane(table); scroll.setBounds(50, 220, 550, 150); add(scroll);

        // Total
        lTotal = new JLabel("Total Amount:"); lTotal.setBounds(50, 380, 100, 25); add(lTotal);
        tTotal = new JTextField("0.00"); tTotal.setBounds(180, 380, 150, 25); tTotal.setEditable(false); add(tTotal);

        // Buttons
        bGenerate = new JButton("Generate & Print Bill"); bGenerate.setBounds(50, 420, 250, 30); add(bGenerate);
        bBack = new JButton("Back"); bBack.setBounds(320, 420, 120, 30); add(bBack);

        bGenerate.addActionListener(this);
        bBack.addActionListener(this);

        setVisible(true);
    }

    // --- Database Helper Methods (Unchanged) ---
    private void loadMedicines() {
        cbMedicine.removeAllItems();
        String sql = "SELECT med_name FROM medicine ORDER BY med_name";
        try (Connection con = DriverManager.getConnection(DatabaseConfig.URL, DatabaseConfig.USER, DatabaseConfig.PASSWORD);
             Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            
            while (rs.next()) {
                cbMedicine.addItem(rs.getString("med_name"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading medicines: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private MedicineData getMedicineDetails(String medicineName) {
        String sql = "SELECT Med_id, price, quantity FROM medicine WHERE med_name = ?";
        try (Connection con = DriverManager.getConnection(DatabaseConfig.URL, DatabaseConfig.USER, DatabaseConfig.PASSWORD);
             PreparedStatement pst = con.prepareStatement(sql)) {
            
            pst.setString(1, medicineName);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    return new MedicineData(
                        rs.getInt("Med_id"), 
                        rs.getFloat("price"), 
                        rs.getInt("quantity") 
                    );
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error fetching medicine details: " + e.getMessage());
        }
        return null;
    }
    
    private static class MedicineData {
        int id;
        float price;
        int stock;
        public MedicineData(int id, float price, int stock) {
            this.id = id;
            this.price = price;
            this.stock = stock;
        }
    }

    // --- Utility Methods (Unchanged) ---
    private void updateTotal() {
        float total = 0.0f;
        for (int i = 0; i < model.getRowCount(); i++) {
            total += Float.parseFloat(model.getValueAt(i, 3).toString()); 
        }
        tTotal.setText(String.format("%.2f", total));
    }


    // --- Event Handling (Add Medicine unchanged) ---
    public void actionPerformed(ActionEvent ae) {
        
        if (ae.getSource() == bBack) {
            // new WelcomePage(); // Placeholder for navigation
            dispose();
            return;
        }

        if (ae.getSource() == bAddMedicine) {
            try {
                if (cbMedicine.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(this, "No medicines available.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                String medicineName = cbMedicine.getSelectedItem().toString();
                int qty = Integer.parseInt(tQuantity.getText().trim());

                if (qty <= 0) {
                    JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                MedicineData data = getMedicineDetails(medicineName);
                
                if (data == null) {
                    JOptionPane.showMessageDialog(this, "Medicine details not found.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (qty > data.stock) {
                    JOptionPane.showMessageDialog(this, "Insufficient stock. Only " + data.stock + " available.", "Stock Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                float amount = qty * data.price;

                // Add row: Medicine, Quantity, Price, Amount, [Med ID]
                model.addRow(new Object[]{medicineName, qty, data.price, String.format("%.2f", amount), data.id});

                updateTotal();
                tQuantity.setText("1"); 
                
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Enter valid numeric quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }

        // --- Generate Bill Logic (CORRECTED) ---
        if (ae.getSource() == bGenerate) {
            
            int generatedBillId = -1; // Variable to hold the auto-generated ID
            
            try {
                // --- 1. Validation & Data Retrieval ---
                // Removed parsing tBillId since it's now auto-generated
                String custId = tCustId.getText().trim(); 
                String date = tDate.getText().trim();
                float total = Float.parseFloat(tTotal.getText().trim());

                if (custId.isEmpty() || date.isEmpty() || model.getRowCount() == 0 || total <= 0) {
                    JOptionPane.showMessageDialog(this, "Please fill Customer ID, ensure date is correct, and add items to the bill.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // --- 2. Database Transaction Start ---
                try (Connection con = DriverManager.getConnection(DatabaseConfig.URL, DatabaseConfig.USER, DatabaseConfig.PASSWORD)) {
                    con.setAutoCommit(false); // Start transaction

                    // A. Insert into sale table (Bill Header)
                    // *** CORRECTION 2: Use Statement.RETURN_GENERATED_KEYS to get the new ID ***
                    String sqlSale = "INSERT INTO sale (cust_id, date, total_amount) VALUES (?, ?, ?)";
                    try (PreparedStatement pstSale = con.prepareStatement(sqlSale, Statement.RETURN_GENERATED_KEYS)) {
                        
                        pstSale.setString(1, custId);
                        pstSale.setString(2, date);
                        pstSale.setFloat(3, total);
                        pstSale.executeUpdate();

                        // *** CORRECTION 3: Retrieve the generated Bill ID ***
                        try (ResultSet rs = pstSale.getGeneratedKeys()) {
                            if (rs.next()) {
                                generatedBillId = rs.getInt(1);
                                tBillId.setText(String.valueOf(generatedBillId)); // Update UI with the new ID
                            } else {
                                throw new SQLException("Failed to retrieve auto-generated bill ID.");
                            }
                        }
                    }

                    // B. Insert into bill table (Line Items) and Update Stock (medicine table)
                    // Use the generatedBillId for the line items
                    String sqlItem = "INSERT INTO bill (bill_id, medicine, quantity, price) VALUES (?, ?, ?, ?)";
                    String sqlStock = "UPDATE medicine SET quantity = quantity - ? WHERE Med_id = ?"; 
                    
                    try (PreparedStatement pstItem = con.prepareStatement(sqlItem);
                          PreparedStatement pstStock = con.prepareStatement(sqlStock)) {
                        
                        for (int i = 0; i < model.getRowCount(); i++) {
                            // Item data from table model
                            String medName = model.getValueAt(i, 0).toString();
                            int qty = (int) model.getValueAt(i, 1);
                            // Need explicit casting/parsing here because DefaultTableModel stores Object
                            float price = Float.parseFloat(model.getValueAt(i, 2).toString()); 
                            int medId = (int) model.getValueAt(i, 4); 

                            // i. Prepare Bill Item Insert (uses generated Bill ID)
                            pstItem.setInt(1, generatedBillId);
                            pstItem.setString(2, medName); 
                            pstItem.setInt(3, qty);
                            pstItem.setFloat(4, price);
                            pstItem.addBatch();

                            // ii. Prepare Stock Update
                            pstStock.setInt(1, qty);
                            pstStock.setInt(2, medId);
                            pstStock.addBatch();
                        }

                        pstItem.executeBatch();
                        pstStock.executeBatch(); // Execute all stock updates

                    }

                    // --- 3. Transaction Commit ---
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Bill generated successfully! Bill ID: " + generatedBillId + " and stock updated!");
                    
                    // new WelcomePage(); // Placeholder for navigation
                    dispose(); 

                } catch (SQLException sqle) {
                    // --- 4. Transaction Rollback on Error ---
                    try (Connection con = DriverManager.getConnection(DatabaseConfig.URL, DatabaseConfig.USER, DatabaseConfig.PASSWORD)) {
                         con.rollback(); 
                    } catch (SQLException rollbackEx) {
                        System.err.println("Rollback failed: " + rollbackEx.getMessage());
                    }
                    JOptionPane.showMessageDialog(this, "Database Error during transaction: " + sqle.getMessage(), "DB Error", JOptionPane.ERROR_MESSAGE);
                    sqle.printStackTrace();
                }

            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Please check numeric values for Total or Medicine quantity/price.", "Input Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "System Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    public static void main(String[] args) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "MySQL JDBC Driver not found!", "Driver Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SwingUtilities.invokeLater(() -> new GenerateBillForm());
    }
}